/*
# Force RLS on all tables

Ensures RLS is not just enabled but also forced, so no role can bypass it.
Also re-applies all anon SELECT policies to ensure they are active.
*/

ALTER TABLE proteins ENABLE ROW LEVEL SECURITY;
ALTER TABLE proteins FORCE ROW LEVEL SECURITY;

ALTER TABLE units ENABLE ROW LEVEL SECURITY;
ALTER TABLE units FORCE ROW LEVEL SECURITY;

ALTER TABLE employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE employees FORCE ROW LEVEL SECURITY;

ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE categories FORCE ROW LEVEL SECURITY;

ALTER TABLE cuts ENABLE ROW LEVEL SECURITY;
ALTER TABLE cuts FORCE ROW LEVEL SECURITY;

ALTER TABLE processing ENABLE ROW LEVEL SECURITY;
ALTER TABLE processing FORCE ROW LEVEL SECURITY;

ALTER TABLE processing_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE processing_items FORCE ROW LEVEL SECURITY;

ALTER TABLE processing_byproducts ENABLE ROW LEVEL SECURITY;
ALTER TABLE processing_byproducts FORCE ROW LEVEL SECURITY;

ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings FORCE ROW LEVEL SECURITY;
